exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('kagal_data').del();
  
  // Inserts sample voter data with Marathi names and complete information
  await knex('kagal_data').insert([
    {
      id: 1,
      EFullName: 'Ganesh Ashok Patil',
      MFullName: 'गणेश अशोक पाटील',
      'Mobile No': '9876543210',
      'Serial No': '001',
      'Booth No': '45',
      'Booth Name': 'Shri Shahu High School',
      'Ebooth Name': 'श्री शाहू हायस्कूल',
      EPIC: 'ABC1234567',
      Address: 'Kagal, Kolhapur, Maharashtra',
      Age: '35',
      Gender: 'Male',
      Part: '45-A',
      'Part Name': 'Kagal Urban',
      'House No': '123',
      'Father Name': 'Ashok Ramchandra Patil',
      'MFather Name': 'अशोक रामचंद्र पाटील',
      Relation: 'Self'
    },
    {
      id: 2,
      EFullName: 'Sunita Ramesh Khade',
      MFullName: 'सुनिता रमेश खाडे',
      'Mobile No': '9876543211',
      'Serial No': '002',
      'Booth No': '45',
      'Booth Name': 'Shri Shahu High School',
      'Ebooth Name': 'श्री शाहू हायस्कूल',
      EPIC: 'ABC1234568',
      Address: 'Kagal, Kolhapur, Maharashtra',
      Age: '42',
      Gender: 'Female',
      Part: '45-A',
      'Part Name': 'Kagal Urban',
      'House No': '124',
      'Father Name': 'Ramesh Vitthal Khade',
      'MFather Name': 'रमेश विठ्ठल खाडे',
      Relation: 'Wife'
    },
    {
      id: 3,
      EFullName: 'Kashinath Dinakar Ghatage',
      MFullName: 'कशिनाथ दिनकर घाटगे',
      'Mobile No': '9876543212',
      'Serial No': '003',
      'Booth No': '46',
      'Booth Name': 'Vidya Mandir School',
      'Ebooth Name': 'विद्या मंदिर शाळा',
      EPIC: 'ABC1234569',
      Address: 'Kagal, Kolhapur, Maharashtra',
      Age: '58',
      Gender: 'Male',
      Part: '46-B',
      'Part Name': 'Kagal Rural',
      'House No': '89',
      'Father Name': 'Dinakar Shankar Ghatage',
      'MFather Name': 'दिनकर शंकर घाटगे',
      Relation: 'Self'
    },
    {
      id: 4,
      EFullName: 'Priya Suresh Jadhav',
      MFullName: 'प्रिया सुरेश जाधव',
      'Mobile No': '9876543213',
      'Serial No': '004',
      'Booth No': '46',
      'Booth Name': 'Vidya Mandir School',
      'Ebooth Name': 'विद्या मंदिर शाळा',
      EPIC: 'ABC1234570',
      Address: 'Kagal, Kolhapur, Maharashtra',
      Age: '29',
      Gender: 'Female',
      Part: '46-B',
      'Part Name': 'Kagal Rural',
      'House No': '156',
      'Father Name': 'Suresh Dattatray Jadhav',
      'MFather Name': 'सुरेश दत्तात्रय जाधव',
      Relation: 'Daughter'
    },
    {
      id: 5,
      EFullName: 'Rajesh Maruti Shinde',
      MFullName: 'राजेश मारुती शिंदे',
      'Mobile No': '9876543214',
      'Serial No': '005',
      'Booth No': '47',
      'Booth Name': 'Government Primary School',
      'Ebooth Name': 'सरकारी प्राथमिक शाळा',
      EPIC: 'ABC1234571',
      Address: 'Kagal, Kolhapur, Maharashtra',
      Age: '45',
      Gender: 'Male',
      Part: '47-C',
      'Part Name': 'Kagal East',
      'House No': '78',
      'Father Name': 'Maruti Govind Shinde',
      'MFather Name': 'मारुती गोविंद शिंदे',
      Relation: 'Self'
    },
    {
      id: 6,
      EFullName: 'Anita Prakash More',
      MFullName: 'अनिता प्रकाश मोरे',
      'Mobile No': '9876543215',
      'Serial No': '006',
      'Booth No': '47',
      'Booth Name': 'Government Primary School',
      'Ebooth Name': 'सरकारी प्राथमिक शाळा',
      EPIC: 'ABC1234572',
      Address: 'Kagal, Kolhapur, Maharashtra',
      Age: '38',
      Gender: 'Female',
      Part: '47-C',
      'Part Name': 'Kagal East',
      'House No': '92',
      'Father Name': 'Prakash Baban More',
      'MFather Name': 'प्रकाश बाबन मोरे',
      Relation: 'Wife'
    }
  ]);
};